### ISSUE TITLE
Rename code files to follow a consistent naming structure.

### ISSUE THREAD

**Issue by lcarasik** [Jhaefner/TORCHE#11]
Currently, the files for pressure drop do not follow a consistent naming structure (examples below). Can we make sure these are consistent for easier use of the toolbox?

Ex:

ZukakuskasPressureDrop.py
Gaddis-Gnielinski Pressure Drop Model

Can be made consistent using the following:

dP_Zukakuskas.py
dP_Gaddis_Gnielinski.py

**Comment by Jhaefner** [comment]
Two pull requests have been made regarding changes to the ReadMe and the master example.
One consolidated Python script has been added while the old individual scripts were moved to the LEGACY Folder and a README was added.
