### ISSUE TITLE
Bias: Need to determine how the percent error was calculated and is it appropriate based off this information. – Ask Jonah what exactly he did again.

### ISSUE THREAD

**Issue by lcarasik** [Jhaefner/TORCHE#27]
Need to address calculating mean percent error (or other metric) based on log transformed values as opposed to based on non-transformed. To help prevent higher percent errors (or other metric) from heavily biasing the mean value.

**Comment by Jhaefner** [comment]
I didn't transform the data at all. I just took the absolute value of the difference between the accepted value and the calculated value and divided by the accepted value. Then took the mean of this value across all the data points.
