### ISSUE TITLE
Add Kays and London pressure drop model

### ISSUE THREAD

**Issue by lcarasik** [Jhaefner/TORCHE#5]
The Kays and London pressure drop model needs to be added for comparison for future with in a design study.

**Comment by lcarasik** [comment]
This has been address with recent commits adding the Kay's and London Model.

**Comment by Jhaefner** [comment]
Actually the recent commits added the Gnielinski Model, Kays and London model as not yet been added.

**Comment by Jhaefner** [comment]
Considering this an artifact of this project now. Removing Issue.
